{% set name = "rfi-file-monitor" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rfi-file-monitor-{{ version }}.tar.gz
  sha256: e3ba05918f96572afc667fd9786fe65043c2b1dfdcc03b2263b034eb1facbc24

build:
  number: 0
  entry_points:
    - rfi-file-monitor = rfi_file_monitor:main
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
  run:
    - boto3
    - munch
    - paramiko
    - pygobject
    - python
    - pyyaml
    - watchdog
    - gtk3
    - adwaita-icon-theme
    - librsvg
    - bugsnag

test:
  imports:
    - rfi_file_monitor
    - rfi_file_monitor.application
    - rfi_file_monitor.applicationwindow
    - rfi_file_monitor.file
    - rfi_file_monitor.job
    - rfi_file_monitor.operation
    - rfi_file_monitor.preferences
    - rfi_file_monitor.preferenceswindow
    - rfi_file_monitor.utils
    - rfi_file_monitor.operations.dummy_operation
    - rfi_file_monitor.operations.local_copier
    - rfi_file_monitor.operations.s3_uploader
    - rfi_file_monitor.operations.sftp_uploader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RosalindFranklinInstitute/rfi-file-monitor
  summary: Easy to use file monitor GUI with user-definable operations
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
