{% set name = "rfi-file-monitor" %}
{% set version = "0.1.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rfi-file-monitor-{{ version }}.tar.gz
  sha256: 30cb68a77e047f9a2e7f01d662d9df0728eff2220563b29c6ce0275d58c4d12e

build:
  number: 1
  entry_points:
    - rfi-file-monitor = rfi_file_monitor:main
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
  run:
    - boto3
    - munch
    - paramiko
    - pygobject
    - python
    - pyyaml
    - watchdog
    - gtk3
    - adwaita-icon-theme
    - librsvg
    - bugsnag
    - glib
    - dropbox
    - keyring

test:
  imports:
    - rfi_file_monitor
    - rfi_file_monitor.application
    - rfi_file_monitor.applicationwindow
    - rfi_file_monitor.file
    - rfi_file_monitor.job
    - rfi_file_monitor.operation
    - rfi_file_monitor.preferences
    - rfi_file_monitor.preferenceswindow
    - rfi_file_monitor.operations.dropbox_uploader
    - rfi_file_monitor.operations.dummy_operation
    - rfi_file_monitor.operations.local_copier
    - rfi_file_monitor.operations.s3_uploader
    - rfi_file_monitor.operations.sftp_uploader
    - rfi_file_monitor.utils
    - rfi_file_monitor.utils.widgetparams
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RosalindFranklinInstitute/rfi-file-monitor
  summary: Easy to use file monitor GUI with user-definable operations
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
